---
- name: Configurar e instalar agente zabbix
  hosts: all
  vars:
    zserver: zabbix.4linux.com.br
  tasks:

  - name: Instalar repositorio CentOS
    get_url:
      url: http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
      dest: /tmp/zabbix-release-3.0-1.el7.noarch.rpm
      mode: 0777

  - name: Instalar repositorio Debian
    get_url:
      url: http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix-release/zabbix-release_3.0-1+jessie_all.deb
      dest: /tmp/zabbix-release_3.0-1+jessie_all.deb
      mode: 0777

  - name: Executando zabbix.rpm
    yum: name=/tmp/zabbix-release-3.0-1.el7.noarch.rpm state=present
    when: ansible_distribution == "CentOS"

  - name: Executando zabbix.deb
    apt: deb=/tmp/zabbix-release_3.0-1+jessie_all.deb
    when: ansible_distribution == "Debian"

  - name: Instalar agente zabbix CentOS
    yum: name=zabbix-agent state=latest
    when: ansible_distribution == "CentOS"

  - name: Instalar agente zabbix
    apt: name=zabbix-agent state=latest
    when: ansible_os_family == "Debian"

  - name: Preparar arquivo de configuração
    template: src=./zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644

  - name: Iniciar agente zabbix
    service: name=zabbix-agent state=started enabled=yes
